batch_size: 4
iters: 40000

train_dataset:
  type: Dataset
  dataset_root: ./
  train_path: train_list.txt
  num_classes: 34
  transforms:
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: ./
  val_path: val_list.txt
  num_classes: 34
  transforms:
    - type: Normalize
  mode: val

optimizer:
  type: sgd

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1,0.4]

learning_rate:
  value: 0.0005
  decay:
    type: poly
    power: 0.9
    end_lr: 0.0


