_base_: '../_base_/wrap.yml'

model:
  type: GCNet
  backbone:
    type: HRNet_W18
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz 
    has_se: False
  gc_channels: 512
  ratio: 0.25
  backbone_indices: [-1,0]
  enable_auxiliary_loss: True
  align_corners: False


