_base_: '../_base_/wrap.yml'

model:
  type: OCRNet
  backbone:
    type: HRNet_W18
    # pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
    has_se: False
  num_classes: 34
  backbone_indices: [0]
  