
_base_: '../_base_/cityscapes.yml'


model:
  type: OCRNet
  backbone:
    type: HRNet_W48
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
  num_classes: 15
  backbone_indices: [0]
  pretrained: null
  # https://bj.bcebos.com/paddleseg/dygraph/ccf/fcn_hrnetw48_rs_256x256_160k/model.pdparams
