_base_: '../_base_/wrap.yml'

model:
  type: DANet
  backbone:
    type: ResNet50_vd
    output_stride: 8
  num_classes: 34
  backbone_indices: [2, 3]

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1, 1, 1, 0.4]
